### ISSUE TITLE
Consider using NSSpellChecker to derive your word count

### ISSUE THREAD

**Issue by danielpunkass** [mattgemmell/MGWordCounter#2]
I do word counting in MarsEdit and originally did something like you did here, rolling one's own notion of what it means to be a word, etc. A lot of this can be thrown away if you decide you trust Apple's interpretation. You just do something like:

numberOfWords = [[NSSpellChecker sharedSpellChecker] countWordsInString:theString language:nil];

**Comment by mattgemmell** [comment]
Hi Daniel,

I noticed the NSSpellChecker API, and did run a few tests with it. There were three main reasons I chose not to go with it:
1. It's OS X only, and I wanted the same results on both OS X and iOS.
2. It produces a count that's not consistent with my gold standard, BBEdit.
3. Since it's just a single fire-and-wait call, it's not readily cancellable.

For those reasons, I decided to go with NSString's -enumerateSubstringsInRange: with the NSStringEnumerationByWords option. So it's still opaque to me, and I don't decide what constitutes a word! That API is cancellable within the enumeration block, exists on both platforms, and produces the same counts as BBEdit in the test cases I have. :)

**Comment by danielpunkass** [comment]
Well, those are all very fine reasons. Maybe it's me who needs to change his approach!

**Comment by vslavik** [comment]
A better choice would be `CFStringTokenizer`, available on both platforms. It has the notable advantage of actually counting words correctly, even for languages that don't use whitespace to separate words:

> CFStringTokenizer allows you to tokenize strings into words, sentences or paragraphs in a language-neutral way. It supports languages such as Japanese and Chinese that do not delimit words by spaces, as well as de-compounding German compounds. You can obtain Latin transcription for tokens. It also provides language identification API.
